//
//  MinerView.swift
//  cryptic
//
//  Created by Nils Grob on 20.01.21.
//

import SwiftUI

struct MinerView: View {
    @State var wallet:String = ""
    @State var coins:Double = 0.0
    let screenWidth = UIScreen.main.bounds.width
    let screenHeight = UIScreen.main.bounds.height
    var body: some View {
        VStack{
            Spacer().frame(height:20)
            Image("Miner").resizable().frame(width: 200, height: 200)
            Text("Please enter a Wallet-UUID to which\n the money generated by the miner should be paid ").multilineTextAlignment(.center).foregroundColor(.white)
            TextField("Wallet UUID", text: $wallet).background(Color("ForegroundColor")).cornerRadius(5).frame(width: screenWidth * 0.8)
            Spacer().frame(height: 20)
            if(wallet != ""){
                Slider(value: $coins).frame(width: screenWidth * 0.8)
                Text("\(coins) MC/h").foregroundColor(.white).font(.title)
                Text("\(coins*24) MC/d").foregroundColor(.white).font(.title)
            }
            Spacer()
            
        }.frame(width: screenWidth).background(Color("BackgroundColor")).ignoresSafeArea()
        
    }
}

struct MinerView_Previews: PreviewProvider {
    static var previews: some View {
        MinerView()
    }
}
